on:
  push:
    branches:
      - setup-ci

jobs:
  check:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup toolchain
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test

      - name: Build
        run: npm run build:prod

      - name: Prepare for deploy
        run: |
          cp public/index.html dist/index.html
          cp public/style.css dist/style.css

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
