on:
  push:
    branches:
      - setup-ci

jobs:
  check:
    name: check and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup toolchain
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test
